### ISSUE TITLE
[Bug]: There are severe mosaics at higher bit rates（>2Mb/s）.

### ISSUE THREAD

**Issue by GrizaJ** [ThibaultBee/StreamPack#86] opened 2023-11-21 10:39 UTC
### Version

2.5.2

### Environment that reproduces the issue

DJI RC pro (android 10)
one plus (android 13)
even rk3399 (android 7)

### RTMP/SRT/... Server

srt

### Audio configuration

No audio.

### Video configuration

H.264
resolution:1920x1080
bitrate:>3Mbps
I had try2M, 3M,4M,5M. only the <2M is satisfactory.

### Is it reproducible in the demos application?

Yes

### Reproduction steps

1. set config.1920x1080 & about 5Mbps.
2. set ip & streamip.
3. Record Screen
4. Observe play phenomenon,(VLC or other player)

### Expected result

Keep it clear and fluid.

### Actual result

it is fluid with severe mosaics. The top 10% of the picture is clear, and the bottom 90% is the severe mosaics. It's like losing a lot of  key frames.

### Additional context

1. I had use OBS to push same server with 10M,,and it is clean and fluid. so I don't think it's the server limitation.
2. I had try option the #setSockFlag(xx,xx) method. but it seems to be invalid. I down know Whether it has anything to do with Tsmuxer.

Thank you very much. You shared an excellent project

**Comment by ThibaultBee** [comment] 2023-11-21 17:18
Hi there,
From what you say, the first thing that pops in my mind is a network issues.
I understand that it works for OBS, but somehow the Wi-Fi of your phone might not be good enough to handle a lot of bandwidth.
There is a way to check that frames correctly goes to your server. Could you display at a schedule rate SRT `stats` such as `pktSndLossTotal`?

Also, it could be an issue with the profile but I don't see why the bitrate changes something. You can try by forcing the `VideoConfig.profile` to `AVCProfileBaseline`.

Also, I don't understand your environment:

> DJI RC pro (android 10)
> one plus (android 13)
> even rk3399 (android 7)

What do you mean exactly?

**Comment by GrizaJ** [comment] 2023-11-22 12:13
GOOD NEWS ! 
I test  with my srt-live-server which running ubuntu.  
it is clean and no any mosaics. So the problem is the link to the network. (my god!)

but, It is very difficult to adjust srt parameters in a poor network.

**Comment by ThibaultBee** [comment] 2023-11-22 21:30
Well, SRT do it best but sometime it can not recover from poor network. It is not magic.

If you want to improve transmission, here are few things that could work:
- reduce the video bitrate
- increase latency

If you are looking to tune SRT parameters, you should contact SRT team.

**Comment by ThibaultBee** [comment] 2023-12-03 10:19
I guess the issue is resolved by now.
Feel free to reopen it if needed.

**Closed by ThibaultBee** 2023-12-03 10:19 UTC
Labels: bug
